### ISSUE TITLE
[COS] Improve error handling observation missing

### ISSUE THREAD

**Issue by oyvindeide** [equinor/semeio#41] opened 2020-02-18 13:16 UTC
Correlated Observations Scaling:

Error handling: better error message when observation specified in group do not exist in dataset

Example:
`['OBS', 'STD'] should be present in DataFrame index, missing: set(['OBS', 'STD'])`

It is not clear how to reproduce this error;
 - what is the "dataset" in this case?
 - observations specified in which group? (input config file?)

**Comment by jondequinor** [comment] 2020-03-10 11:05
I am going to assume errors on the semeio side of the configuration.

**Comment by markusdregi** [comment] 2020-03-10 12:31
I think so yes

**Comment by jondequinor** [comment] 2020-03-10 13:22
I'm unable to reproduce, so I've asked the original reporter for more information.

**Comment by oyvindeide** [comment] 2020-03-10 13:23
Seems to happen when we are trying to access observational data, but it´s not present. Could be because the obervation is preset, but is filtered out before being accessed.

**Comment by tralsos** [comment] 2020-03-10 13:32
What I meant is if the user has a typo in the configuration of the CORRELATED_OBSERVATION_SCALING and writes an observation name that does not exist in the obsfile used for the prior run. I can make a test to reproduce it if it doesn't occour for you.

**Comment by tralsos** [comment] 2020-03-10 18:10
I think this error message only occur if the erroneous key also have a `*` in the name, e.g. I had 
`key : ALB_GIIP*`   but could instead have used `key : ALB_GIIP`
With the typo `key : AL_GIIP*` I get this cryptic error message reported above, while for the typo `key : AL_GIIP`  the error message is 

> "Key: AL_GIIP has no data"

, which is good.

**Comment by jondequinor** [comment] 2020-03-15 11:25
For the `snake_oil` case, I've tried to reproduce this with the following configuration:
```CALCULATE_KEYS:
  keys: [key: WPR_DIFF_1*]
UPDATE_KEYS:
  keys: [key: WPR_DIFF_1*]
```
I can not reproduce this issue. @tralsos can you provide a test-case? Komodo `testing-py2` should work fine come Monday.

**Comment by jondequinor** [comment] 2020-03-23 11:27
Reproducible with the following config: 
```
-
    CALCULATE_KEYS:
        keys: [key: AMP*]
-
    CALCULATE_KEYS:
        keys: [key: WWCT_1*]
```
run against e.g. the `snake_oil` observations.

**Comment by sondreso** [comment] 2020-04-03 14:55
Closed by https://github.com/equinor/semeio/pull/78

**Closed by sondreso** 2020-04-03 14:55 UTC
