### ISSUE TITLE
Tests leaks storage folder in root

### ISSUE THREAD

**Issue by markusdregi** [equinor/semeio#72] opened 2020-03-19 06:39 UTC
After running the tests in a clean semeio tree I get a `storage` folder in the root folder. I suspect one of the tests using snake oil to be the sinner as `storage` contains a single folder named `snake_oil`.

**Comment by oyvindeide** [comment] 2020-03-26 09:49
Yes, this is most likely a `libres` issue though as `EnkfMain` is used in some integration tests, so probably not copied from snake oil, but rather dumped from `EnkFMain` in teardown. This started occuring when we merged: https://github.com/equinor/libres/commit/9ca9544e3ab0e5141c4d0c3017c2c5f9bc410f64. I´ll close this but feel to reopen if that is not the root cause.

**Comment by markusdregi** [comment] 2020-03-26 12:01
Yes, but this has been possible to isolate in other tests by setting the paths correctly and running in a temp-folder. I don't this we should give up so easily ;)

**Comment by oyvindeide** [comment] 2020-03-26 12:38
Sure, but many of the tests are already running in a temp-folder, we would have to double wrap them in a second temp folder (I think), then perhaps we should but something like this in the root `conftest.py`:
```
@pytest.mark.fixture(autouse=True)
def move_to_tmpdir(tmpdir):
    with tmpdir.as_cwd():
        yield
```
That will move all tests to it´s own tmpdir, ugly, but then we only have one place to delete it once the underlying problem gets fixed.

**Comment by oyvindeide** [comment] 2020-09-22 09:33
I was a bit annoyed by this, so I had a deeper look. My conclusion is that we can not really solve this at the moment. I tried wrapping all the tests in a separate tmpdir, which did not work. I then looked at when the `storage` folder is created, and it is when all the tests are completed, during tear down. It will also occur if a test using `EnkFMain` fails, regardless of how many tmpdirs it is wrapped in.

The reason it happens in the first place is most likely because the workflow class is internalizing `ert`.

Note that this also happens in `libres`, if any test using `EnkFMain` fails, it will leave behind a `storage` folder in the root folder.

Now, there is one thing that does work, which is calling `gc.collect()` after the tests producing storage have completed, but am not convinced that is a good solution.

**Closed** 2020-09-23 06:19 UTC
