### ISSUE TITLE
Problem combining COS workflow with ES-MDA

### ISSUE THREAD

**Issue by eivindsm** [equinor/semeio#85] opened 2020-04-20 12:46 UTC
I have been testing the COS workflow, and come across an issue (which I think is a bug). When running ES_MDA from a clean start (empty storage) I get the following error:
eism@st-linrgs272:/project/fmu/users/eism/ERT_analytical/ert> ert gui config_tenobs_scale.ert 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-eism'
Running MDA ES for 3  iterations	4.0, 2.0, 1.0
Running MDA ES on (weights normalized)	4.583, 2.291, 1.146
All 50 active jobs complete and data loaded.
The script 'CorrelatedObservationsScalingJob' caused an error while running:
Invalid job
	Key: obsvalues has no dataAll 50 active jobs complete and data loaded.

However, the ES algorithm  runs as announced, and moreover ES-MDA also runs if the ES algorithm has been run prior to execution.

My setup is to be found here: eism@st-linrgs272:/project/fmu/users/eism/ERT_analytical/ert

**Comment by markusdregi** [comment] 2020-04-21 05:44
Hmm 🤔 To which stage did you hook the workflow?

**Comment by eivindsm** [comment] 2020-04-21 05:55
-------------------------------------------------------------------
-- Workflows
-------------------------------------------------------------------
LOAD_WORKFLOW workflows/jobs/WORKFLOW_COS
HOOK_WORKFLOW WORKFLOW_COS PRE_UPDATE

**Comment by oyvindeide** [comment] 2020-09-21 15:51
Can you check if this is still an issue? I was not able to reproduce locally starting from no storage with the poly case. I looked at your setup, and everything looked fine, but did not want to run it in the fear of messing up anything. If you run it again, can you run it with `unstable`?

**Comment by oyvindeide** [comment] 2020-10-27 13:19
I will close this as I have not been able to reproduce, feel to re-open if this happens again.

**Closed by oyvindeide** 2020-10-27 13:19 UTC
